platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
	pod 'AppwiseCore', :path => '../'
	pod 'AppwiseCore/CoreData', :path => '../'
	pod 'AppwiseCore/UI', :path => '../'
end
