disabled_rules:
  - line_length

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - collection_alignment
  - convenience_type
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Example/Pods
  - Example/Application/Sources/Generated

identifier_name:
  excluded:
    - vc
    - nvc
    - db

custom_rules:
  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: '(?:UIImage\(named: ".+"\))|(?:#imageLiteral\(resourceName: ".+"\))|(?:UIColor\(named: ".+"\))'
    message: "Use Asset.<asset> instead"
  swiftgen_colors:
    name: "SwiftGen Colors"
    regex: '(?:#colorLiteral\(red: .+?, green: .+?, blue: .+?, alpha: .+?\))'
    message: "Use ColorName.<color> instead"
