swiftlint_version: 0.51.0

disabled_rules:
  - anonymous_argument_in_multiline_closure
  - conditional_returns_on_newline
  - discouraged_object_literal
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - file_name
  - file_name_no_space
  - file_types_order
  - ibinspectable_in_extension
  - implicitly_unwrapped_optional
  - indentation_width
  - line_length
  - missing_docs
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - pattern_matching_keywords
  - prefer_nimble
  - prohibited_interface_builder
  - required_deinit
  - strict_fileprivate
  - switch_case_on_newline
  - type_contents_order
  - untyped_error_in_catch
  - vertical_whitespace_between_cases

opt_in_rules:
  - all

excluded:
  - .build
  - Package.swift
  - Sources/Core/Generated
  - Example

identifier_name:
  excluded:
    - vc
    - nvc
    - db

nesting:
  type_level: 2

file_header:
  required_pattern: |
                    \/\/
                    \/\/ AppwiseCore
                    \/\/ Copyright © 2024 Wisemen
                    \/\/

custom_rules:
  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
    message: "Use Asset.<asset> instead"
    severity: error
  swiftgen_colors:
    name: "SwiftGen Colors"
    regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
    message: "Use ColorName.<color> instead"
    severity: error
  swiftgen_fonts:
    name: "SwiftGen Fonts"
    regex: 'UIFont(\.init)?\(name: ?"?.+"?, ?size:.+?\)'
    message: "Use FontFamily.<family>.<variant>.size(<size>) instead"
    severity: error
  swiftgen_storyboard_scenes:
    name: "SwiftGen Storyboard Scenes"
    regex: '(UIStoryboard\(name: ?"?.+"?, ?bundle:.+\))|(instantiateViewController\(withIdentifier:.+?\))|(instantiateInitialViewController\(\))'
    message: "Use StoryboardScene.<storyboad>.<scene>.instantiate() instead"
    severity: error
  swiftgen_storyboard_segue_perform:
    name: "SwiftGen Storyboard Segue Identifier"
    regex: 'performSegue\(withIdentifier: ?"?.+"?, ?sender:.+\)'
    message: "Use perform(segue: StoryboardSegue.<storyboard>.<segue>, sender: <sender>) instead"
    severity: error
  swiftgen_storyboard_segue_prepare:
    name: "SwiftGen Storyboard Segue Prepare"
    regex: 'segue.identifier'
    message: "Use StoryboardSegue.<storyboard>(segue) instead"
    severity: error
  swiftgen_strings:
    name: "SwiftGen Strings"
    regex: 'NSLocalizedString'
    message: "Use L10n.key instead"
    severity: error
